export {
  PAGE_TEMPLATE_KEYS,
  PAGE_TEMPLATE_OPTIONS,
  PAGE_LOCALES,
  STRUCTURED_PAGE_KIND,
  createStructuredPageStarter,
  detectPageContentMode,
  flattenStructuredDocument,
  parseJsonContent,
  parseStructuredPageDocument,
  prettyPrintPageContent,
  suggestPageTemplate,
  summarizePageContent,
  wrapLongFormAsStructuredDocument,
} from "@mealnova/shared";

export type {
  PageAction,
  PageContentMode,
  PageContentSummary,
  PageLocale,
  PageMetric,
  PageSection,
  PageSectionCards,
  PageSectionCta,
  PageSectionHero,
  PageSectionProse,
  PageSectionStats,
  PageTemplateKey,
  StructuredPageDocument,
} from "@mealnova/shared";
